# Generated by Django 4.1 on 2023-08-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotogradia',
            new_name='Fotografia',
        ),
    ]
