# Generated by Django 4.1 on 2023-08-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_rename_fotogradia_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('LUA', 'Lua'), ('GALÁXIA', 'Galáxia')], default='', max_length=100),
        ),
    ]
